spring:
  h2:
    console:
      enabled: true
  datasource:
    name: testdb
    driverClassName: org.h2.Driver
    #initialization-mode: always
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=TRUE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 80
  servlet:
    context-path: /
  
  #todo: make sure to always enable security in production
security:
  basic:
    enabled: false

logging:
  level:
    root: ERROR
    com:
      krovvidi: DEBUG
    org:
      springframework:
        security: ERROR
        web: ERROR
      hibernate: ERROR        
      apache:
        commons:
          dbcp2: ERROR
  path: c:\tools\logs\event-api
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'  
#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.
  
#default project info followed by actual injected pom-specified values.
project:
  name: event-api
  version: 0.1
  description: Event Rest API
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}