INSERT INTO EVENT(EVENT_DATE, EVENT_MONTH, EVENT_YEAR, EVENT_TYPE, EVENT_GROUP, FIRST_NAME, LAST_NAME, MAIDEN_NAME, EMAIL_ID, PHONE_NUMBER, ZIP_CODE)
VALUES (29,11,1976, 'Birth', 'Relatives', 'Suresh', 'Krovvidi', null, 'suresh.krovvidi@gmail.com', '+1-513-370-4097', '45040');

INSERT INTO EVENT(EVENT_DATE, EVENT_MONTH, EVENT_YEAR, EVENT_TYPE, EVENT_GROUP, FIRST_NAME, LAST_NAME, MAIDEN_NAME, EMAIL_ID, PHONE_NUMBER, ZIP_CODE)
VALUES (22,3,1978, 'Birth', 'Relatives', 'Srividya', 'Krovvidi', 'Mallapragada', 'srividya.krovvidi@gmail.com', '+1-513-808-5115','45040');