INSERT INTO EVENT(EVENT_DATE, EVENT_MONTH, EVENT_YEAR, EVENT_TYPE, EVENT_GROUP, FIRST_NAME, LAST_NAME, MAIDEN_NAME, EMAIL_ID, PHONE_NUMBER, ZIP_CODE)
VALUES (1,11,1989, 'Birth', 'Relatives', 'John', 'Doe', null, 'john.doe@company.com', '+1-234-234-2342', '54321');

INSERT INTO EVENT(EVENT_DATE, EVENT_MONTH, EVENT_YEAR, EVENT_TYPE, EVENT_GROUP, FIRST_NAME, LAST_NAME, MAIDEN_NAME, EMAIL_ID, PHONE_NUMBER, ZIP_CODE)
VALUES (2,3,1987, 'Birth', 'Relatives', 'Sam', 'K', 'Smith', 'sam.k.smith@test.com', '+1-123-123-1234','12345');
