DROP TABLE EVENT;

CREATE TABLE EVENT (
	EVENT_DATE INTEGER,
	EVENT_MONTH INTEGER,
	EVENT_YEAR INTEGER,
	EVENT_TYPE CHAR(10),
	EVENT_GROUP CHAR(20),
	FIRST_NAME CHAR(100),
	LAST_NAME CHAR(100),
	MAIDEN_NAME CHAR(100),
	EMAIL_ID CHAR(100),
	PHONE_NUMBER VARCHAR(20),
	ZIP_CODE CHAR(5)
);